### ISSUE TITLE
Single sensor for Solar

### ISSUE THREAD

**Issue by snoopydooper** [estruyf/homebridge-solis-sensors#1]
Hello and thank you.

This is the only plug-in I am able to successfully get working with my Solis setup.

I only have solar generation with no battery. Would it be possible to have a single standalone sensor for generation kw only?

**Comment by estruyf** [comment]
Hey @snoopydooper, that is why I created the project 🤓.

I updated the plugin (0.1.0-beta.3008619) so that you can define which sensors you want to enable/disable. The new configuration looks as follows:

```json
{
  ...
  "platforms": [
    ...
    {
      "keyId": "key",
      "keySecret": "secret",
      "stationId": "station id",
      "platform": "SolisSensors",
      "batterySensor": true,
      "solarSensor": true,
      "netSensor": true,
      "loadSensor": true
    }
  ]
}
```
