### ISSUE TITLE
Required details

### ISSUE THREAD

**Issue by liam4330** [estruyf/homebridge-solis-sensors#4]
Hi,

Where would I find the required credentials for

‘keyID’, ‘keysecret’ and ‘stationID’

thanks

**Comment by estruyf** [comment]
Hi, @liam4330, you can find the ID and Secret for Solis in your Solic Cloud portal: https://www.soliscloud.com/#/apiManage

Station ID can be retrieved from the URL when opening your "plant":

- Navigate to: https://www.soliscloud.com/#/station
- Click on the plant you want to monitor
- On the URL you get a query string parameter: `stationdetail_1`, the value is your `stationId`.

**Comment by liam4330** [comment]
Great, now working
